services:
  postgres-db-ci/cd:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.docker
    volumes:
      - postgres-ci__cd:/var/lib/postgresql/data

  node-app-actions:
    container_name: node-app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres-db-ci/cd
    env_file:
      - .env.docker

volumes:
  postgres-ci__cd:
