services:
  postgres-db-ci/cd:
    image: postgres
    container_name: postgres-db-ci/cd
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.docker.test

  node-app-actions:
    container_name: node-app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres-db-ci/cd
    env_file:
      - .env.docker.test
